### ISSUE TITLE
Add Flathub Flatpak repository by default?

### ISSUE THREAD

**Issue by electricduck** [sodaliterocks/bootable#1]
We should consider adding Flathub as a default repository (alongside AppCenter and Fedora), for a number of reasons:

1. This is a repo people will be adding often, and since Fedora OSTree advocates pulling all your apps from it, it would make sense.
2. AppCenter is only for "curated" elementaryOS apps, so many apps people use on a daily basis  will never be published to it.
3. Software (due to hopefully be replaced by AppCenter if it ever supports `rpm-ostree`) looks a little... wrong... without it, since nothing appears to load when you initially open it. Once you start browsing around it becomes clear apps are there, just none of AppCenter's are being chosed as "Editor's Choice's" (urgh) so the home view appears blank. See below screenshot.

![Screenshot from 2022-01-12 09 20 54](https://user-images.githubusercontent.com/1594644/149102102-ba467f36-8830-47bf-9a94-ade6591cb7ea.png)

**Comment by ACertainTopfi** [comment]
As the repo set via lorax-embed-flatpaks.tmpl is only utilized for the image build and install process the AppCenter repo will not be accessible on the system after installation by default. For that we will have to add a few postinstall commands. Nothing complicated, I will write up a script.

**Comment by ACertainTopfi** [comment]
The build images now add the flatpak remotes to the system. This has been accomplished by adding two post install comments to the build script: https://github.com/sodaliterocks/bootable/commit/55867baccc9a5771b5e023268c5cc2ad8e39eed1

**Comment by ACertainTopfi** [comment]
I have to look into this, for some reason the postinstall command does import the appcenter, but not the flathub repo.

**Comment by ACertainTopfi** [comment]
Was able to get this working without the post install commands by making changes to the lorax-embeds fork. These have been implemented with: https://github.com/sodaliterocks/bootable/commit/4cd6275106369e5fea884d32856c2bb52eb3888d
Images are now build with flathub and appcenter included. I will have to tidy the build script and especially the embeds repo in the coming days, but from testing, it seems to me that the installations are now at a reliable stage.
