### ISSUE TITLE
Embed AppCenter Flatpak apps

### ISSUE THREAD

**Issue by electricduck** [sodaliterocks/bootable#2]
Right now [this is commented out in `build.sh`](https://github.com/sodaliterocks/bootable/blob/devel/build.sh#L89-L93) as a bug seems to occur when attempting to embed it.

Currently, this is being handled by the `sodalite-install-appcenter-flatpak` script already. However, apps are delayed installing (as also happens on a rebased Silverblue) which is janky, and it would be just nice to have it work without relying on the script. The script itself won't cause any issues once this issue is fixed: it'll just run and then do nothing since everything is already setup!

**Comment by ACertainTopfi** [comment]
This is easily adressable by linking to the .flatpakrepo file provided by Elementary. lorax-embeds-flatpaks.tmpl expects that file type, rather than a direct link to the repo, unless the repo is a collection of Docker containers.

**Comment by ACertainTopfi** [comment]
https://github.com/sodaliterocks/fedora-lorax-templates/blob/main/ostree-based-installer/lorax-embed-flatpaks.tmpl provides a (crude but functional) fork that allows us to use both the appcenter and flathub repo during installation, allowing us to ship the freedesktop.gl runtime and with it Epiphany. This has been implemented with: https://github.com/sodaliterocks/bootable/commit/55867baccc9a5771b5e023268c5cc2ad8e39eed1
